id: P003075
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:38:49.409325
source_metadata:
  id: bdr:W739
  title: ཚད་མའི་སྤྱི་དོན་རིགས་རྒྱན་ཆེན་མོ།
  author: ''
  volumes:
    61f7079eb7bb4bde9ffbf8747ac58588:
      image_group_id: I1KG10850
      title: ''
      volume_number: 1
      total_pages: 524
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
