id: P003075
initial_creation_type: ocr
source_metadata:
  id: bdr:W739
  title: ཚད་མའི་སྤྱི་དོན་རིགས་རྒྱན་ཆེན་མོ།
  author: ''
  volumes:
    61f7079eb7bb4bde9ffbf8747ac58588:
      image_group_id: I1KG10850
      title: ''
      volume_number: 1
      total_pages: 524
      base_file: v001.txt
