id: IBAF42141
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:01:27+00:00'
last_modified: '2022-06-07T17:23:44.630774+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W739
  title: ཚད་མའི་སྤྱི་དོན་རིགས་རྒྱན་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1741':
      image_group_id: I1KG10850
      title: ''
      total_pages: 524
      order: 1
      base_file: 1741.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
